#!/bin/bash
# Fail if Stride.xcodeproj is not exactly what project.yml generates.
#
#   scripts/ci/check_xcodegen_drift.sh
#
# Stride.xcodeproj is committed (Xcode, CI and the release scripts open it directly), and
# project.yml is the source of truth. They drift when someone edits one without the other —
# e.g. a target added in Xcode's UI that the next `xcodegen generate` (build-appstore.sh
# runs one) silently deletes, or a project.yml change whose regenerated project was never
# committed, so CI builds the old one.
#
# Output depends on the XcodeGen version, so this refuses to judge with any version but the
# pinned one (CI installs exactly that; see XCODEGEN_VERSION in .github/workflows/ci.yml).
set -uo pipefail

EXPECTED_XCODEGEN="2.45.3"   # keep in sync with XCODEGEN_VERSION in .github/workflows/ci.yml

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/../.."

actual="$(xcodegen --version 2>/dev/null | sed -n 's/^Version: *//p')"
if [[ "$actual" != "$EXPECTED_XCODEGEN" ]]; then
    echo "  ✗ xcodegen ${actual:-not installed}, but the committed project is generated by $EXPECTED_XCODEGEN."
    exit 3
fi

xcodegen generate --quiet || { echo "  ✗ xcodegen generate failed"; exit 1; }

status=0
if ! git diff --exit-code --stat -- Stride.xcodeproj; then
    echo "  ✗ Stride.xcodeproj as generated from project.yml differs from the committed one (diff above)."
    status=1
fi
# New files (a scheme for a new target, say) are not in `git diff`.
untracked="$(git ls-files --others --exclude-standard -- Stride.xcodeproj)"
if [[ -n "$untracked" ]]; then
    echo "  ✗ xcodegen generated files that are not committed:"
    echo "$untracked" | sed 's/^/      /'
    status=1
fi
if (( status != 0 )); then
    echo "    Run \`xcodegen generate\` (XcodeGen $EXPECTED_XCODEGEN) and commit Stride.xcodeproj."
    exit 1
fi
echo "  ✓ Stride.xcodeproj matches project.yml (XcodeGen $EXPECTED_XCODEGEN)"
